#!/bin/sh  /etc/rc.common
. /lib/functions.sh
# Copyright (C) 2011 OpenWrt.org 

log() {
	logger -t "30-mount" "$@"
}

sanitize() {
	sed -e 's/[[:space:]]\+$//; s/[[:space:]]\+/_/g' "$@"
}

if [ ! -f /tmp/bootend.file ]; then
	sleep 10
	while [ ! -f /tmp/bootend.file ]; do
		sleep 1
	done
	log "Delay Block Mount for boot up"
fi

blkdev=`dirname $DEVPATH` 
if [ `basename $blkdev` != "block" ]; then 
	device=`basename $DEVPATH` 
	if echo $device | grep -q "mtdblock"; then
		exit 0
	fi
	if echo $device | grep -q "mmcblk"; then
		exit 0
	fi
	if echo $device | grep -q "CF_1GB"; then
		exit 0
	fi

	case "$ACTION" in 
		add)
			DEVN=${DEVNAME:0:3}
			MODEL=$(sanitize "/sys/block/$DEVN/device/model")
			if [ -d /etc/samba ]; then
				uci delete samba.$device
				uci set samba.$device=sambashare
				uci set samba.$device.name=$MODEL$DEVNAME
				uci set samba.$device.path=/mnt/$device
				uci set samba.$device.read_only=no
				uci set samba.$device.guest_ok=yes
				uci commit samba
				/etc/init.d/samba restart
				log "/mnt/$device shared as $MODEL$DEVNAME"
			fi
		;; 
		remove) 
			log "remove /mnt/$device"
			if [ -d /etc/samba ]; then
				uci delete samba.$device
				uci commit samba
			fi
		;; 
	esac 
fi
